  # --- Queueing System ---
  redis:
    image: redis:7.0.5
    container_name: panopticon_redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
  
  # --- Worker Nodes (Scalable) ---
  # worker:
  #   build: .
  #   command: celery -A panopticon.worker worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - neo4j
  #     - milvus

volumes:
  neo4j_data:
  neo4j_logs:
  milvus_etcd:
  milvus_minio:
  milvus_data:
  opensearch_data:
  redis_data:
